apiVersion: apps/v1
kind: Deployment
metadata:
  name: rates-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rates
  template:
    metadata:
      labels:
        app: rates
    spec:
      containers:
        - name: rates
          image: husievdmytro/rates
          env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_HOST
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_DB
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: NODE_ENV
---
apiVersion: v1
kind: Service
metadata:
  name: rates-srv
spec:
  selector:
    app: rates
  type: ClusterIP
  ports:
  - name: rates
    protocol: TCP
    port: 3000
    targetPort: 3000
